---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
    
- name: install dependency
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: give GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

  notify: start and enable docker

- name: Update repo list
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Add config file docker
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root

- name: Add config file docker 
  file: 
    path: /etc/systemd/system/docker.service.d/override.conf
    state: touch
    owner: root
    group: root
  
- name: Make docker configuration file
  template:
    src: docker-service.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify: restart docker

- name: Restart service docker and daemon-reload to pick up config changes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Get the latest release tag from Docker Compose GitHub
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: yes
  register: release_info

- name: Install or upgrade docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ release_info.json.tag_name }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'
    force: yes

